### ISSUE TITLE
[CLOSED] Unable to locate package ibus-avro-trusty

### ISSUE THREAD

**Issue by ugcoder** [ugcoder/avro#61]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [FaisalHaq](https://github.com/FaisalHaq)**
_Sunday Apr 27, 2014 at 14:38 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/62_

----

I'm unable to install "ibus-avro-trusty" but no problem installing "ibus-avro-saucy"

Added key, sudo apt-get update all done...

user@user-Aspire-4736Z:~$ sudo apt-get install ibus-avro-trusty
[sudo] password for user: 
Reading package lists... Done
Building dependency tree
Reading state information...Done
E: Unable to locate package ibus-avro-trusty

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Sunday Apr 27, 2014 at 15:10 GMT_

----

There was a complication. Can you try again now ? Also dont forget to remove any other version of ibus avro before installing ibus-avro-trusty.

    sudo apt-get update
    sudo apt-get install ibus-avro-trusty

**Comment by ugcoder** [comment]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FaisalHaq](https://github.com/FaisalHaq)**
_Monday Apr 28, 2014 at 12:18 GMT_

----

Thx it's working now...

**Comment by sadiksikder** [comment]
the same problem again i am facing again
